"""took away user img

Revision ID: 2cfddf084a4d
Revises: 96eb10c5e1ed
Create Date: 2021-06-02 14:52:17.403707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfddf084a4d'
down_revision = '96eb10c5e1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
